### ISSUE TITLE
2024 migration

### ISSUE THREAD

**Issue by tansautn** [cortex42/DownloadWallBypasser#2]
When i came here yesterday, it's sad when see the comment "it's does not work anymore".

So, i tried to make this automation script work again...
There's mine: https://gist.github.com/tansautn/d6abfbfcff5d7eb44fdb83f5abc89383
It's worked. But i dont have time for testing & optimize the script.

So, it would be nice if you can keep update this.

**Comment by fan1200** [comment]
Hi @tansautn 

I tried your script but I wasn't able to fully go to through the process. However; your script inspired me to rethink the whole process and I managed to create a Userscript that automates the process by clicking thru the page, filling in the elements and manipulate some elements on the page. All this results into a working example and eventually a download. When installed/enabled it is just clicking on the track and the rest works automatically (it also autoclose the window).

I hope you don't mind that I borrowed your snippet for the Soundcloud window (I didn't know that was possible too). I also ditched Jquery since it is 2024 and Vanilla JS is powerfull enough to stand on its own feet.

See: https://github.com/fan1200/hypeddit-downloadwall-bypasser-reloaded

**Comment by tansautn** [comment]
@fan1200  Very nice. Thank you. Actually, my script only works with a hypetrack that has one stage to download (just connect & comment).

As I said, I don't have time to test more carefully about other cases. But I'm sure the simple click is enough to pass the hypetrack, then I'm blind on CSS. I had to spend a lot of time identifying the Carousel and trying to increase the steps, and also determine the current step. But due to my CSS skills limitations, I lose.

Your script is very clean, and using observer is a good choice for this case. In fact, there's a `downloadUnlimitedGate` function exposed on the window object. We can still simulate other steps without a click trigger. But again, I don't have time for this. Then my point is just: auto-download when visiting the hypetrack URL.

About the "download configuration," I thought it's difficult for normal users who have no programming skills. So, to make it easier to configure, my idea is: Localstorage Proxy is a reasonable choice. We will only need 1 Floating Element with a few inputs.

BTW: jQuery is still so powerful for me. At least I don't need to do a nonsense thing like QuerySelectorAll then forEach :|
